# Generated by Django 3.2 on 2021-10-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('bio', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
